[package]
name = "yas-application"
version = "0.1.0"
edition = "2021"

[dependencies]
yas_genshin = { path = "../yas-genshin", package = "yas_scanner_genshin" }
log = "0.4"
env_logger = "0.11"

[[bin]]
name = "yas_artifact"
path = "src/bin/yas_artifact.rs"
# build = "build.rs"
